# Generated by Django 2.2 on 2021-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedata',
            name='email_address',
            field=models.CharField(default=1, max_length=200, verbose_name='邮箱地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linedata',
            name='master_people',
            field=models.CharField(default=1, max_length=200, verbose_name='负责人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linedata',
            name='supplier_name',
            field=models.CharField(default=1, max_length=200, verbose_name='供应商名称'),
            preserve_default=False,
        ),
    ]
