# Generated by Django 2.2 on 2021-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_linedata_bandwidth_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='bandwidth_size',
            field=models.CharField(max_length=200, verbose_name='带宽大小(M)'),
        ),
    ]
