# Generated by Django 2.2 on 2021-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210907_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='softdata',
            name='cost',
            field=models.CharField(default=1, max_length=200, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
