# Generated by Django 2.2 on 2021-09-07 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_softdata_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedata',
            name='contract_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='合同签订时间'),
        ),
        migrations.AddField(
            model_name='softdata',
            name='contract_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='合同签订时间'),
        ),
        migrations.AddField(
            model_name='softdata',
            name='cost_single',
            field=models.CharField(default=1, max_length=200, verbose_name='单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softdata',
            name='number_of',
            field=models.CharField(default=1, max_length=200, verbose_name='数量(套)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softdata',
            name='cost',
            field=models.CharField(max_length=200, verbose_name='总价格'),
        ),
    ]
