# Generated by Django 2.2 on 2021-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210907_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='softdata',
            name='license_type',
            field=models.CharField(default=1, max_length=200, verbose_name='许可类型'),
            preserve_default=False,
        ),
    ]
