# Generated by Django 2.2 on 2021-09-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_softdata_license_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softdata',
            old_name='contract_time',
            new_name='contract_time_soft',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='cost',
            new_name='cost_soft',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='delay_date',
            new_name='delay_date_soft',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='email_address',
            new_name='email_address_soft',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='master_people',
            new_name='master_people_soft',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='job_name',
            new_name='soft_name',
        ),
        migrations.RenameField(
            model_name='softdata',
            old_name='supplier_name',
            new_name='supplier_name_soft',
        ),
    ]
