# Generated by Django 3.2.7 on 2021-09-08 09:10

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210908_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='contract_time',
            field=models.DateTimeField(default=time.time, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='delay_date',
            field=models.DateTimeField(default=time.time, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='softdata',
            name='contract_time_soft',
            field=models.DateTimeField(default=time.time, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='softdata',
            name='delay_date_soft',
            field=models.DateTimeField(default=time.time, verbose_name='到期时间'),
        ),
    ]
