# Generated by Django 2.2 on 2021-09-10 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210908_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='contract_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='delay_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='softdata',
            name='contract_time_soft',
            field=models.DateField(default=datetime.datetime.now, verbose_name='合同签订时间'),
        ),
        migrations.AlterField(
            model_name='softdata',
            name='delay_date_soft',
            field=models.DateField(default=datetime.datetime.now, verbose_name='到期时间'),
        ),
    ]
