# Generated by Django 2.2 on 2021-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210910_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedata',
            name='describe_name',
            field=models.CharField(default=1, max_length=200, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
