# Generated by Django 2.2 on 2021-09-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_linedata_describe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linedata',
            name='describe_name',
        ),
    ]
